const Constants = {
  ADD_POST: "ADD_POST",
  UPDATE_NEW_POST_TEXT: "UPDATE_NEW_POST_TEXT",
  UPDATE_NEW_MESSAGE_BODY: "UPDATE_NEW_MESSAGE_BODY",
  SEND_MESSAGE: "SEND_MESSAGE",
};
export default Constants;
